server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    # prueba para ignorar configServer y desplegar eureka
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    #para que no se registre dentro de si mismo
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/
